// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// In production (Vercel), use the proxy path so traffic never hits supabase.co directly.
// This bypasses ISP/firewall blocks. In development, use the real URL.
const SUPABASE_URL =
  import.meta.env.PROD
    ? `${window.location.origin}/supabase`
    : import.meta.env.VITE_SUPABASE_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
